name: 'Just example CI CD using GitHub Actions'

# Trigger the workflow on push events to the 'main' branch
on: 
  push:
    branches: 
      - main

# All the actions to perform
jobs: 
# // un build command to check build failing or not 
  build: 
  # defining operating system
    runs-on: ubuntu-latest
# each steps to perform it may be installing dependencies, defining versions etc
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
  
    