name: 'Just example CI CD using GitHub Actions'

# Trigger the workflow on push events to the 'main' branch
on: 
  push:
    branches: 
      - main

# All the actions to perform
jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Node.js setup
        uses: actions/setup-node@v3
        with: 
          node-version: '20'
    
      - name: Install dependencies
        run: npm install
  
      - name: Run tests
        run: npm test
    