name : 'Just example CI CD using github actions'

# // trigger 
on: 
  push:
    brances: 
    - main

# all the sction perform
jobs: 
  runs-on: ubuntu-latest

  steps: 
  - name: Checkout code
    uses: actions/checkout@3

  - name: nodejs setup
    uses: actions/setup-node@v3
    with: 
      node-version: '18'
    
  - name: Install dependecies
    run: npm install
  
  - name: Run test
    run: npm test